person:
  user-name: 张三
  boss: true
  birth: 2019/12/9
  age: 18
  interests: [篮球, 足球]
  #  interests:
  #    - 篮球
  #    - 足球
  animal: [阿猫, 阿狗]
  score: {english: 80, math: 90}
  salarys: [9999.98, 9999.99]
  pet: {name: 阿狗, weight: 99.999}
  allPets: {sick: [{name: 阿狗, weight: 99.99}, {name: 阿猫, weight: 88.88}, {name: 暗藏, weight: 77.77}],
            health: [{name: 阿花, weight: 199.99}, {name: 阿聪, weight: 222.22}]}


#spring:
#  banner:
#    location:
#    image:
#      bitdepth: 4
#  cache:
#    type: redis
#    redis:
#      time-to-live: 11000